spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tany-ecommerce
  servlet:
    multipart:
      max-file-size: 3MB

imagekit:
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT:your_url_endpoint}
  public-key: ${IMAGEKIT_PUBLIC_KEY:your_public_key}
  private-key: ${IMAGEKIT_PRIVATE_KEY:your_private_key}

mailersend:
  api-token: ${MAILERSEND_API_TOKEN:your_api_token}
  from-email: ${MAILERSEND_FROM_EMAIL:info@domain.com}
  from-name: ${MAILERSEND_FROM_NAME:Tany}

jwt:
  secret: ${JWT_SECRET:your_jwt_secret}

eshop:
  base-url: ${ESHOP_BASE_URL:http://localhost:8080}
