spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tany-ecommerce
  servlet:
    multipart:
      max-file-size: 3MB

imagekit:
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT}
  public-key: ${IMAGEKIT_PUBLIC_KEY}
  private-key: ${IMAGEKIT_PRIVATE_KEY}

mailersend:
  api-token: ${MAILERSEND_API_TOKEN}
  from-email: ${MAILERSEND_FROM_EMAIL:info@tany.sk}
  from-name: ${MAILERSEND_FROM_NAME:Tany.sk}

jwt:
  secret: ${JWT_SECRET}

eshop:
  base-url: ${ESHOP_BASE_URL:http://localhost:8080}
  frontend-url: ${ESHOP_FRONTEND_URL:http://localhost:3000}

security:
  excluded-urls:
    - /api/login/**
    - /api/customer/**
    - /api/carts/**
    - /v3/api-docs/**
    - /swagger-ui/**

logging:
  level:
    org.springframework.security: TRACE
